### ISSUE TITLE
404 on every page

### ISSUE THREAD

**Issue by matteobortolazzo** [Microsoft/aspnet-api-versioning#150]
1.1.0 and 1.1.1 give me this: 
Request successfully matched the route with name 'default' and template '{controller=Home}/{action=Index}/{id?}'.
No actions matched the current request
Request did not match any routes.

1.0.3 works.
Please test before publishing, I've lost almost 2 days of work to find the error.

**Comment by ericvan76** [comment]
For version 1.1+ 
Add `services.UseApiVersioning();`  to your startup.cs

**Comment by irowbin** [comment]
The problem is solved for v1.1.0 Take a look at https://github.com/Microsoft/aspnet-api-versioning/issues/146

**Comment by matteobortolazzo** [comment]
Ok, I've added app.UseApiVersioning(); but it still doesn't work.
*I've also cleaned the solution and recompiled it.

**Comment by irowbin** [comment]
@matteobortolazzo Please post your configuration  of startup class and the controller or an example below.
This works:
Startup.cs
```javascript
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller=Home}/{action=account}");
});

app.UseApiVersioning();
app.MapWhen(x => !x.Request.Path.Value.StartsWith("/api"), builder =>
{
    builder.UseMvc(routes =>
    {
        routes.MapSpaFallbackRoute(
            name: "spa-fallback",
            defaults: new { controller = "Home", action = "Index" });
    });
});
```
HomeController.cs
```javascript
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/[controller]/[action]")] // working 
//[Route("api/v{version:apiVersion}/[controller]")] // not working.
[Produces("application/json")]
public class ValuesController : Controller
{
        
    [HttpGet]
    public IEnumerable<string> Get()
    {
        return new string[] { "value1", "value2" };
    }

        
    [HttpGet("{id}")] // must specify the route parameter otherwise AmbiguousActionException will occur. 
    public string Get(int id)
    {
        return "value";
    }
}
```

**Comment by matteobortolazzo** [comment]
The problem is with controllers with [ApiVersionNeutral] attribute

**Comment by commonsensesoftware** [comment]
@matteobortolazzo can you provide your configuration, skeleton controller, and requested routes? It would help troubleshoot where you are running into trouble. If you have, or can produce, the world's simplest repro, that goes miles into me provide quick answers and/or necessary patching.

While I can certainly appreciate your frustration when things stop working, the test coverage is extensive. There are over 1000 test cases. Unfortunately, it's impossible for me to test every application configuration. Most of the reported issues are simple misconfigurations, but occasionally I find an edge case that triggers a new bug or even a regression [like yesterday :'( ]. Whenever a new combination is discovered, it's added to the acceptance test suite.

Sadly, there is a behavioral change in 1.1 from 1.0 that requires a new configuration setup. It's easy to miss and things just stop working. I looked into failing with an exception when this configuration is missing, but I haven't found a way to make things blow up on you without it - yet. I called the change out in the release notes, updated all the wiki pages, and updated all the sample projects. It's beyond my capability to _make_ people read these things though.

Ultimately, the more information and context you can provide me, the faster I can produce answers. Thanks.

**Comment by TonyCasey** [comment]
Yep, same issue for me on .Net Core 1.1 & 4.6.2

Took me for ages to isolate it. Adding app.UseApiVersioning(); to Configure did the trick.

It will catch everyone I imagine as no-one will expect it.

**Comment by ericvan76** [comment]
It would be great if you can add a quick start to readme.md, rather than
let user drilling down to the project wiki. The wiki is great, but it's too
long, and most of things are not helpful for a starter. And please make
wiki links bigger and clear, make nuget links smaller. Always accidently
clicked into nuget page, which is mostly useless.

Just some suggestions.
Thanks

**Comment by commonsensesoftware** [comment]
Apologies again for all the confusion. It's unfortunate that things had to change this way. It wasn't a _willy-nilly_ decision. The behavioral, breaking change comes as a shock to existing users, but without it there were broken edge cases for 1.0 users.

@matteobortolazzo still hasn't stated that his issue is resolved, but it seems that the consensus here is that making the proposed configuration changes will do the trick. Per a previous conversation with @irowbin in #146, I've updated the wiki to discuss this in the [known limitations](../wiki/Known-Limitations) topic.

When the original readme was created there wasn't a lot of content to go with it. Now that things have matured quite a bit, I agree that the landing page was due for an overhaul. @ericvan76 , per your request, I've updated the landing page. Let me know if you think that makes things more discoverable. I have no intention of _confusing the enemy_. ;) I also added a little tidbit to remind people to check the release notes (with a link). If you have other suggestions, I'm listening. Thanks.

**Comment by ericvan76** [comment]
@commonsensesoftware, the new page looks great! Thanks. :)

**Comment by matteobortolazzo** [comment]
Moving app.UseApiVersioning() after app.UseMvc() did the trick! Thanks everyone!
The next time I'll check the wiki before update :)

**Comment by matteobortolazzo** [comment]
Moving app.UseApiVersioning() after app.UseMvc() did the trick! Thanks everyone!
The next time I'll check the wiki before update :)
