### ISSUE TITLE
Error on Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy

### ISSUE THREAD

**Issue by iceoz** [microsoft/aspnet-api-versioning#552]
I get this error 
"Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.":"Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy"

my code is 
services.AddApiVersioning(o =>
{
o.ReportApiVersions = true;
o.AssumeDefaultVersionWhenUnspecified = true;
o.DefaultApiVersion = new ApiVersion(2, 0);
});

**Comment by supergonzales** [comment]
@iceoz As in #504, .NET Core 3.0 is not yet supported. Use preview for now:

`<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.0.0-preview8.19405.7" />`

**Comment by commonsensesoftware** [comment]
Correct. You need to use the preview version - for now. Working on the official release. It'll be out ASAP. I expect this issue is now resolved. If not, feel free to reopen it. Thanks.

**Comment by abezverkov** [comment]
I havent seen anyone else say anything about it but, Im still getting this issue with 4.1
```
System.Private.CoreLib: Exception while executing function: WebAppProxy. Microsoft.AspNetCore.Mvc.Versioning: Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=4.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```
Clearly I'm doing something wrong.

Project file
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="4.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.0.0-*" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="5.0.0-*" />
  </ItemGroup>
</Project>
```

**Comment by commonsensesoftware** [comment]
@abezverkov 4.1 targets ASP.NET Core 3.1 and .NET Core 3.1. Beyond that, there is **zero** difference from 4.0. I see your application is configured for NET Core 3.0 and not 3.1. Updating that will probably fix it. Unfortunately, API Versioning still multi-targets to ASP.NET 2.2 in order to support OData. It targets .NET Standard 2.0. You'd have to look in the restore logs, but I willing to bet that NuGet couldn't match the .NET Core 3.1 reference and fell back to using the .NET Standard 2.0 version, which is completely wrong. I don't have a good answer for that. I'm not sure there's anything more that I can do to avoid this behavior (a few people seem to have encountered it now).

I hope that helps.

**Comment by ardove** [comment]
Is there a reason why 4.1.1 doesn't support .net standard? Looks like 4.1.0 does...

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.AspNetCore.Mvc.Versioning 4.1.1 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.AspNetCore.Mvc.Versioning 4.1.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)	<obfuscated>	C:\dev\<obfuscated>\src\<obfuscated>\<obfuscated>.csproj	1	

```
